project_id = "strictlyfuel"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "strictlyfuel://"
additional_redirect_urls = ["strictlyfuel://auth/callback"]

[storage]
enabled = true
file_size_limit = "12MiB"

[functions.search-foods]
verify_jwt = false
