import React, { useMemo } from "react";
import { Linking, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { ScreenShell } from "../../components/fuel/ScreenShell";
import { raceById } from "../../data/races";
import { buildRaceFuelPlan, RACE_FUELING_SOURCES } from "../../logic/raceFueling";
import type { FuelInterval, GutTrainingLevel, RaceKind } from "../../types/raceMode";
import { formatDuration } from "../../logic/mealTiming";
import { strictlyColors, strictlyRadius, strictlyType } from "../../theme/strictlyTheme";

export type RacePlanParams = { raceId: RaceKind; durationMinutes: number; bodyWeightKg: number; gutTraining: GutTrainingLevel; intervalMinutes: FuelInterval };

const clock = (minutes: number) => `${Math.floor(minutes / 60)}:${String(minutes % 60).padStart(2, "0")}`;

// The finished plan gets its own page; Race Mode keeps only the choices that build it.
export default function RacePlanScreen({ navigation, route }: any) {
  const { raceId, durationMinutes, bodyWeightKg, gutTraining, intervalMinutes } = route.params as RacePlanParams;
  const plan = useMemo(
    () => buildRaceFuelPlan({ race: raceById(raceId), durationMinutes, bodyWeightKg, gutTraining, intervalMinutes }),
    [raceId, durationMinutes, bodyWeightKg, gutTraining, intervalMinutes]
  );

  return <ScreenShell title="Race plan" back onBack={() => navigation.goBack()}>
    <View style={styles.summary}><Text style={styles.summaryEyebrow}>{plan.race.name.toUpperCase()}</Text><Text style={styles.summaryValue}>{plan.totalTargetCarbs}g</Text><Text style={styles.summaryLabel}>planned during-race carbohydrates</Text><View style={styles.summaryStats}><View><Text style={styles.summaryStatValue}>{plan.totalPackedCarbs}g</Text><Text style={styles.summaryStatLabel}>PACKED</Text></View><View><Text style={styles.summaryStatValue}>{formatDuration(plan.durationMinutes)}</Text><Text style={styles.summaryStatLabel}>EST. TIME</Text></View><View><Text style={styles.summaryStatValue}>{plan.intervalMinutes}m</Text><Text style={styles.summaryStatLabel}>RHYTHM</Text></View></View></View>

    <Text style={styles.planTitle}>Before the start</Text><View style={styles.preRace}><Ionicons name="restaurant-outline" size={20} color={strictlyColors.text} /><View style={styles.preRaceCopy}><Text style={styles.preRaceValue}>About {plan.preRaceCarbs}g carbs</Text><Text style={styles.preRaceText}>Use a familiar low-fat, low-fiber meal roughly 2–3 hours before the start. A small tested top-up close to the gun can be handled in Today.</Text></View></View>

    <Text style={styles.planTitle}>What to pack</Text>
    {plan.segments.map((segment) => <View key={segment.label} style={styles.segmentCard}><View style={styles.segmentHead}><View><Text style={styles.segmentTitle}>{segment.label}</Text><Text style={styles.segmentMeta}>{formatDuration(segment.durationMinutes)} · {segment.rate ? `${segment.rate}g/hour` : "No eating during this segment"}</Text></View><Text style={styles.segmentTarget}>{segment.targetCarbs}g</Text></View>{segment.items.length ? segment.items.map((item) => <View key={item.name} style={styles.packRow}><View style={styles.packCount}><Text style={styles.packCountText}>{item.count}×</Text></View><View style={styles.packCopy}><Text style={styles.packName}>{item.name}</Text><Text style={styles.packNote}>{item.totalCarbs}g total · {item.note}</Text></View></View>) : <Text style={styles.noFuel}>Fuel before the swim. Begin planned intake once you are safely settled on the bike.</Text>}</View>)}

    <Text style={styles.planTitle}>Fuel timeline</Text><View style={styles.timeline}>{plan.timeline.map((stop, index) => <View key={`${stop.minute}-${index}`} style={styles.stop}><View style={styles.stopTime}><Text style={styles.stopTimeText}>{clock(stop.minute)}</Text></View><View style={styles.stopCopy}><Text style={styles.stopTitle}>{stop.label}</Text><Text style={styles.stopText}>Aim for about {stop.carbs}g carbs in this interval.</Text></View></View>)}</View>

    <View style={styles.practice}><Ionicons name="shield-checkmark-outline" size={21} color={strictlyColors.accentText} /><Text style={styles.practiceText}>{plan.evidenceNote}</Text></View>
    <View style={styles.hydration}><Text style={styles.hydrationTitle}>Fluids and sodium stay personal</Text><Text style={styles.hydrationText}>Strictly will not invent an exact hydration number without your tested sweat rate, weather, and course access. Use your rehearsed plan and aid-station map, and avoid forcing fluid beyond thirst.</Text></View>
    <Text style={styles.planTitle}>Research behind the range</Text>{RACE_FUELING_SOURCES.map((source) => <TouchableOpacity key={source.url} style={styles.source} onPress={() => Linking.openURL(source.url)}><Text style={styles.sourceText}>{source.title}</Text><Ionicons name="open-outline" size={15} color={strictlyColors.textSoft} /></TouchableOpacity>)}
    <Text style={styles.disclaimer}>Race Mode is practical sports-nutrition guidance, not medical advice. Athletes with diabetes, GI disease, kidney or cardiovascular conditions, or medication-related needs should use an appropriately qualified clinician or sports dietitian.</Text>
  </ScreenShell>;
}

const styles = StyleSheet.create({
  summary: { padding: 20, borderRadius: strictlyRadius.xlarge, backgroundColor: strictlyColors.ink, borderWidth: 1, borderColor: strictlyColors.border }, summaryEyebrow: { fontFamily: strictlyType.semibold, color: strictlyColors.sage, fontSize: 11, letterSpacing: 1.1 }, summaryValue: { marginTop: 8, fontFamily: strictlyType.bold, color: strictlyColors.accentText, fontSize: 56, letterSpacing: -2.4, fontVariant: ["tabular-nums"] }, summaryLabel: { fontFamily: strictlyType.regular, color: strictlyColors.inverseTextSoft, fontSize: 12 }, summaryStats: { marginTop: 18, paddingTop: 15, flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: strictlyColors.overlayLine }, summaryStatValue: { fontFamily: strictlyType.bold, color: strictlyColors.white, fontSize: 14 }, summaryStatLabel: { marginTop: 3, fontFamily: strictlyType.semibold, color: strictlyColors.sage, fontSize: 11, letterSpacing: 1.1 },
  planTitle: { marginTop: 26, marginBottom: 9, fontFamily: strictlyType.bold, color: strictlyColors.text, fontSize: 19 }, preRace: { flexDirection: "row", gap: 11, padding: 15, borderRadius: strictlyRadius.large, backgroundColor: strictlyColors.cream }, preRaceCopy: { flex: 1 }, preRaceValue: { fontFamily: strictlyType.bold, color: strictlyColors.text, fontSize: 14 }, preRaceText: { marginTop: 4, fontFamily: strictlyType.regular, color: strictlyColors.textSoft, fontSize: 11, lineHeight: 15 },
  segmentCard: { marginBottom: 9, padding: 15, borderRadius: strictlyRadius.large, backgroundColor: strictlyColors.surface, borderWidth: 1, borderColor: strictlyColors.border }, segmentHead: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, segmentTitle: { fontFamily: strictlyType.bold, color: strictlyColors.text, fontSize: 16 }, segmentMeta: { marginTop: 3, fontFamily: strictlyType.regular, color: strictlyColors.textSoft, fontSize: 11 }, segmentTarget: { fontFamily: strictlyType.bold, color: strictlyColors.accentText, fontSize: 17 }, packRow: { flexDirection: "row", gap: 10, marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: strictlyColors.border }, packCount: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: strictlyColors.lime }, packCountText: { fontFamily: strictlyType.bold, color: strictlyColors.onLime, fontSize: 12 }, packCopy: { flex: 1 }, packName: { fontFamily: strictlyType.bold, color: strictlyColors.text, fontSize: 12, textTransform: "capitalize" }, packNote: { marginTop: 3, fontFamily: strictlyType.regular, color: strictlyColors.textSoft, fontSize: 11, lineHeight: 14 }, noFuel: { marginTop: 12, fontFamily: strictlyType.regular, color: strictlyColors.textSoft, fontSize: 11, lineHeight: 15 },
  timeline: { borderRadius: strictlyRadius.large, overflow: "hidden", borderWidth: 1, borderColor: strictlyColors.border }, stop: { minHeight: 61, padding: 11, flexDirection: "row", alignItems: "center", gap: 11, backgroundColor: strictlyColors.surface, borderBottomWidth: 1, borderBottomColor: strictlyColors.border }, stopTime: { width: 53, height: 34, borderRadius: strictlyRadius.pill, alignItems: "center", justifyContent: "center", backgroundColor: strictlyColors.cream }, stopTimeText: { fontFamily: strictlyType.semibold, color: strictlyColors.text, fontSize: 11 }, stopCopy: { flex: 1 }, stopTitle: { fontFamily: strictlyType.bold, color: strictlyColors.text, fontSize: 11 }, stopText: { marginTop: 2, fontFamily: strictlyType.regular, color: strictlyColors.textSoft, fontSize: 11 },
  practice: { marginTop: 13, flexDirection: "row", gap: 10, padding: 15, borderRadius: strictlyRadius.large, backgroundColor: strictlyColors.cream }, practiceText: { flex: 1, fontFamily: strictlyType.regular, color: strictlyColors.text, fontSize: 11, lineHeight: 16 }, hydration: { marginTop: 9, padding: 15, borderRadius: strictlyRadius.large, backgroundColor: strictlyColors.surface, borderWidth: 1, borderColor: strictlyColors.border }, hydrationTitle: { fontFamily: strictlyType.bold, color: strictlyColors.text, fontSize: 12 }, hydrationText: { marginTop: 4, fontFamily: strictlyType.regular, color: strictlyColors.textSoft, fontSize: 11, lineHeight: 15 },
  source: { minHeight: 46, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 13, marginBottom: 7, borderRadius: strictlyRadius.medium, backgroundColor: strictlyColors.surface }, sourceText: { flex: 1, fontFamily: strictlyType.medium, color: strictlyColors.text, fontSize: 11 }, disclaimer: { marginTop: 12, fontFamily: strictlyType.regular, color: strictlyColors.textSoft, fontSize: 11, lineHeight: 15, textAlign: "center" },
});
